# Generated by Django 3.1.7 on 2021-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0002_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.CharField(max_length=1200, verbose_name="Description"),
        ),
    ]
