# Generated by Django 3.1.7 on 2021-12-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0005_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to='image/project/multiple/')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.project')),
            ],
        ),
    ]
