# Generated by Django 3.1.7 on 2021-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0007_remove_projectimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="picture",
            field=models.ImageField(
                default="default.jpg",
                max_length=1000,
                upload_to="image/project/multiple/",
            ),
            preserve_default=False,
        ),
    ]
