# Generated by Django 3.1.7 on 2021-12-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0008_projectimage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(default='file/profile/cv/default_cv.pdf', max_length=1000, upload_to='file/profile/cv/'),
        ),
    ]
