# Generated by Django 4.2.3 on 2023-08-19 10:29

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0011_auto_20211223_0700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                default="favicon.ico",
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Image/Settings/Logo",
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="logo.png",
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Image/Settings/Logo",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailapp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pricingkeyword",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professionalskillhighlight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                default="file/profile/cv/default_cv.pdf",
                max_length=1000,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="file/profile/cv/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="image/profile/default_profile.jpg",
                max_length=1000,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="image/profile/",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="image/project/project.jpg",
                max_length=1000,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="image/project/",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="picture",
            field=models.ImageField(
                max_length=1000,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="image/project/multiple/",
            ),
        ),
        migrations.AlterField(
            model_name="projectkeyword",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skillkeyword",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="technicalskillhighlight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="image",
            field=models.ImageField(
                default="image/profile/default_profile.jpg",
                max_length=1000,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="image/profile/",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workhighlight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
