# Generated by Django 4.2.3 on 2023-09-09 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "profile_settings",
            "0012_alter_appsettings_favicon_alter_appsettings_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appsettings",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="emailapp",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="pricing",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="pricingkeyword",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="professionalskillhighlight",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="projectimage",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="projectkeyword",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="skillkeyword",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="sociallink",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="technicalskillhighlight",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="testimony",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="workhighlight",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="pricingkeyword",
            name="pricing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="profile_settings.pricing",
            ),
        ),
        migrations.AlterField(
            model_name="professionalskillhighlight",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_skills",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="profile_settings.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectkeyword",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="profile_settings.project",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="skillkeyword",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="profile_settings.skill",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="technicalskillhighlight",
            name="skill_keyword",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="profile_settings.skillkeyword",
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonies",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work",
                to="profile_settings.profile",
            ),
        ),
        migrations.AlterField(
            model_name="workhighlight",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="profile_settings.work",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appsettings",
            unique_together={("user", "app_name")},
        ),
        migrations.AlterUniqueTogether(
            name="emailapp",
            unique_together={("profile", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="pricing",
            unique_together={("profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="pricingkeyword",
            unique_together={("pricing", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="professionalskillhighlight",
            unique_together={("profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="projectimage",
            unique_together={("project", "picture")},
        ),
        migrations.AlterUniqueTogether(
            name="projectkeyword",
            unique_together={("project", "technology")},
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skillkeyword",
            unique_together={("skill", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="sociallink",
            unique_together={("profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="technicalskillhighlight",
            unique_together={("skill_keyword", "percentage")},
        ),
        migrations.AlterUniqueTogether(
            name="testimony",
            unique_together={("profile", "testimony")},
        ),
        migrations.AlterUniqueTogether(
            name="workhighlight",
            unique_together={("work", "name")},
        ),
    ]
