# Generated by Django 4.2.3 on 2023-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0014_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cv_file",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.URLField(),
        ),
    ]
