# Generated by Django 4.2.3 on 2023-11-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_activitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ("-datetime",)},
        ),
    ]
