# Generated by Django 4.2.3 on 2023-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "experience",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Experience"
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ARCHIVE", "ARCHIVE"),
                            ("APPLIED", "APPLIED"),
                            ("NOT_APPLIED", "NOT_APPLIED"),
                        ],
                        default="NOT_APPLIED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("deadline", models.CharField(max_length=200, verbose_name="Deadline")),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="JobSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=200, verbose_name="Site Name"),
                ),
                ("job_list_link", models.URLField(verbose_name="Job List Link")),
                (
                    "job_link_element",
                    models.CharField(max_length=100, verbose_name="Job Link Element"),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("static", "static"),
                            ("dynamic", "dynamic"),
                            ("api_endpoints", "api_endpoints"),
                        ],
                        default="static",
                        max_length=15,
                        verbose_name="Site TYpe",
                    ),
                ),
                (
                    "name_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Name Element",
                    ),
                ),
                (
                    "experience_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Experience Element",
                    ),
                ),
                (
                    "description_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Description Element",
                    ),
                ),
                (
                    "organization_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Organization Element",
                    ),
                ),
                (
                    "address_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Address Element",
                    ),
                ),
                (
                    "qualification_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Qualification Element",
                    ),
                ),
                (
                    "attribute_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Attribute Element",
                    ),
                ),
                (
                    "deadline_element",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Job Deadline Element",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Qualification"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="job",
            name="job_site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.jobsite",
            ),
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Attribute")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
