# Generated by Django 4.2.3 on 2023-11-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Letter Name")),
                ("file", models.URLField(null=True)),
                ("text", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cv", models.URLField(null=True)),
                ("cover_letter", models.TextField(null=True)),
                (
                    "application_type",
                    models.CharField(max_length=200, verbose_name="Application Method"),
                ),
                ("status", models.CharField(max_length=200, verbose_name="Status")),
                (
                    "feedback",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Feedback"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Feedback Type"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.letter",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
