# Generated by Django 4.2.3 on 2023-12-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_letter_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.CharField(max_length=400, verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="organization",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Organization"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "WAITING"),
                    ("FAILED", "FAILED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                default="WAIT",
                max_length=200,
                verbose_name="Status",
            ),
        ),
    ]
