# Generated by Django 4.2.3 on 2023-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_deadline_alter_job_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Name"),
        ),
    ]
