# Generated by Django 4.2.3 on 2023-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.CharField(max_length=700, verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Experience"
            ),
        ),
    ]
