"""
Django settings for MyPortfolio project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCAL_FILE_DIR = os.path.join(BASE_DIR, 'MyPortfolio')

MEDIA_ROOT = os.path.join(BASE_DIR, 'MyPortfolio/Uploads')

MEDIA_URL = '/Uploads/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(hacsofe)tiogb@_(k9h9_$w(lyw=d4u+0jy61pui(ur53h_lf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

#
# Google Drive Storage Settings
#

GOOGLE_DRIVE_STORAGE_SERVICE_EMAIL  =  "elkanahmalonza@gmail.com" 
GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = os.path.join(BASE_DIR , "MyPortfolio/client_secret1.json")
GOOGLE_DRIVE_STORAGE_MEDIA_ROOT = 'my-portfolio' # OPTIONAL


# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    'profile_settings.apps.ProfileSettingsConfig',
    'projects.apps.ProjectsConfig',
    'admin.apps.AdminConfig',
    'gdstorage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyPortfolio.urls'

TEMPLATES = [
    ***REMOVED***
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': ***REMOVED***
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        ***REMOVED***,
    ***REMOVED***,
]

WSGI_APPLICATION = 'MyPortfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = ***REMOVED***
    'default': ***REMOVED***
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    ***REMOVED***
***REMOVED***


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    ***REMOVED***,
]

# Security Settings
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'profile_settings/static')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'profile_settings/static'),
    os.path.join(BASE_DIR, 'admin/static'),
)

django_heroku.settings(locals())


try:
    from .local_settings import *
except ImportError:
    pass
