# Generated by Django 4.2.3 on 2023-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_articlecategory_user_articleseries_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Keyword"),
        ),
        migrations.AlterField(
            model_name="articleseries",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Keyword"),
        ),
    ]
