# Generated by Django 4.2.3 on 2023-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_article_options_alter_articlecategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
